spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=test;encrypt=true;trustServerCertificate=true
    username: test
    password: test
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  sql:
    init:
      mode: always
      schema-locations: file:./sql/init/schema.sql
      data-locations: file:./sql/init/data.sql
  batch:
    initialize-schema: always
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
